### ISSUE TITLE
Feat: Format ReadMe and Add Suggestions

### ISSUE THREAD

**Issue by Olanetsoft** [Olanetsoft/awesome-hackathon-projects#5]

**Comment by Mannuel25** [comment]
Hello @Olanetsoft , I'd love to take this up. Here's my suggestion:
- Display the projects in a table format with the following details:
   - Name of the project (URL included), the description, developer(s) that worked on it.

**Comment by johnwinifred** [comment]
Hello, Please can I also work on this project
